using System;

/// <summary>
/// Pure rules for the Chinese team's electric dual-gear drivetrain.
/// Gear 1 is Recover and gear 2 is Go.  The consecutive-use counter is
/// intentionally kept outside this class so the same rules can be used by
/// the player loop, AI, and EditMode tests.
/// </summary>
public static class ChinaGearShiftRules
{
    public const int RecoverGear = 1;
    public const int GoGear = 2;

    public readonly struct Result
    {
        public Result(int targetGear, int consecutiveCount, int speedCardCount,
            int additionalHeat, int cooldown)
        {
            TargetGear = targetGear;
            ConsecutiveCount = consecutiveCount;
            SpeedCardCount = speedCardCount;
            AdditionalHeat = additionalHeat;
            Cooldown = cooldown;
        }

        public int TargetGear { get; }
        public int ConsecutiveCount { get; }
        public int SpeedCardCount { get; }
        public int AdditionalHeat { get; }
        public int Cooldown { get; }
    }

    public static bool IsGo(int gear) => gear == GoGear;
    public static bool IsRecover(int gear) => gear == RecoverGear;

    /// <summary>
    /// Resolves a free switch between Go and Recover and advances the
    /// consecutive-use chain. Switching modes resets the chain to one.
    /// </summary>
    public static Result Resolve(int currentGear, int currentConsecutiveCount, int requestedGear)
    {
        int current = ClampMode(currentGear);
        int target = ClampMode(requestedGear);
        int count = current == target && currentConsecutiveCount > 0
            ? currentConsecutiveCount + 1
            : 1;

        if (IsGo(target))
        {
            // Go #1 = 3 cards; Go #2+ = 4 cards. Heat is generated by the
            // electric overclock, not by the act of switching modes.
            int heat = Math.Min(3, Math.Max(0, count - 1));
            return new Result(target, count, count == 1 ? 3 : 4, heat, 0);
        }

        // Recover is always one card. Cooling decays 3 -> 2 -> 1 -> 0.
        return new Result(target, count, 1, 0, Math.Max(0, 4 - count));
    }

    /// <summary>
    /// Small deterministic AI policy from the design document: recover when
    /// hot or after a long Go chain, otherwise alternate modes for efficiency.
    /// </summary>
    public static int ChooseAiGear(int currentGear, int consecutiveCount,
        int speedCardsInHand, float heatRatio, float heatWarningThreshold)
    {
        if (heatRatio >= heatWarningThreshold || speedCardsInHand <= 0)
            return RecoverGear;

        // Go → Go → Recover is the intended efficient rhythm.  Recovering
        // after the second consecutive Go keeps the AI from entering the
        // fourth-card overclock by default; players may still choose to push
        // the chain manually when the track position justifies it.
        if (IsGo(currentGear) && consecutiveCount >= 2)
            return RecoverGear;

        if (IsRecover(currentGear))
            return GoGear;

        return GoGear;
    }

    /// <summary>
    /// Returns whether China AI must leave Go because projected corner heat is
    /// outside its configured risk budget or cannot be paid after already
    /// committed overclock/missing-card heat. Negative inputs are treated as
    /// zero so malformed tuning data cannot create free heat capacity.
    /// </summary>
    public static bool ShouldForceRecoverForCorner(
        int projectedCornerHeat,
        int committedHeat,
        int availableEngineHeat,
        int affordableCornerHeat)
    {
        int cornerHeat = Math.Max(0, projectedCornerHeat);
        int committed = Math.Max(0, committedHeat);
        int available = Math.Max(0, availableEngineHeat);
        int tolerance = Math.Max(0, affordableCornerHeat);
        return cornerHeat > tolerance || cornerHeat + committed > available;
    }

    public static int ClampMode(int gear)
    {
        return gear <= RecoverGear ? RecoverGear : GoGear;
    }

    public static int GetCooldown(int gear, int consecutiveCount)
    {
        if (IsGo(ClampMode(gear))) return 0;
        int count = consecutiveCount > 0 ? consecutiveCount : 1;
        return Math.Max(0, 4 - count);
    }

    public static int GetSpeedCardCount(int gear, int consecutiveCount)
    {
        if (IsGo(ClampMode(gear)))
            return consecutiveCount > 1 ? 4 : 3;
        return 1;
    }
}
